// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ti9aPG6amtJ1yM9mcP5qikOzq25KHYk',
    appId: '1:109576140067:android:963436acd949af9c8bc896',
    messagingSenderId: '109576140067',
    projectId: 'relief-513c5',
    databaseURL: 'https://relief-513c5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'relief-513c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmzkmAPVBojxlmE-RwWoghKjKWzaRlVE',
    appId: '1:109576140067:ios:d46e38f7771325e18bc896',
    messagingSenderId: '109576140067',
    projectId: 'relief-513c5',
    databaseURL: 'https://relief-513c5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'relief-513c5.firebasestorage.app',
    iosClientId: '109576140067-bq242fn63bcc5u16qs4qsk1avm7b7h7n.apps.googleusercontent.com',
    iosBundleId: 'com.ayodele.tech.reliefApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzt1MBo7uvm_GOoBx6iOFFZYt6Gp5fMu8',
    appId: '1:109576140067:web:eab54340b070b2498bc896',
    messagingSenderId: '109576140067',
    projectId: 'relief-513c5',
    authDomain: 'relief-513c5.firebaseapp.com',
    databaseURL: 'https://relief-513c5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'relief-513c5.firebasestorage.app',
    measurementId: 'G-6ZGDSDKQM6',
  );

}